V5 and the road to a Marketplace-like experience (#50)
* Add a marketplace-style solution template.  Also a number of bug fixes and enhancements:
* Add template version-number support, so that multiple releases can be published to S3
* Fix an issue in automate.yaml where the PublicIp wasn't available in the Outputs, so it bombed
* Fix an issue where the dots appended to the domain name caused issues

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* Marketplace v5 - initial working version

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* move final_stage to its own configset, to resolve issues with purging Automate files too early

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* Cost savings part 1: enable gp2 storage for RDS, shrink default instance sizes in marketplace.yaml

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* Cost savings pt 2: Make the number of DB backups tunable and lower the default value

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* Elasticsearch cost reduction, allow 2 instead of 3

Signed-off-by: Irving Popovetsky <irving@popovetsky.com>

* Update images

* Major cost reductions for the marketplace stack

Signed-off-by: Irving Popovetsky <irving@chef.io>

* ES6 is not supported with chef-server today

Signed-off-by: Irving Popovetsky <irving@chef.io>

* Improve browser and CLI launch experience

Signed-off-by: Irving Popovetsky <irving@chef.io>

* Fix one stray template version

Signed-off-by: Irving Popovetsky <irving@chef.io>

* fixes #51, fixes #52, fixes #53, bump version to 5.0.2

Signed-off-by: Irving Popovetsky <irving@chef.io>

* Increase Automate setup timeout to give smaller instances time to finish.  Update AMIs for TCP SACK vulnerability

Signed-off-by: Irving Popovetsky <irving@chef.io>

* Fix the redirect_uri for Supermarket

Signed-off-by: Irving Popovetsky <irving@chef.io>

* majorly revamp the Pre-reqs doc to be much clearer

Signed-off-by: Irving Popovetsky <irving@chef.io>

* New feature:  Provide an Automate admin password instead of the file reading shenanigans

Signed-off-by: Irving Popovetsky <irving@chef.io>

diff --git a/chef_server_ha.yaml b/chef_server_ha.yaml
--- a/chef_server_ha.yaml
+++ b/chef_server_ha.yaml
@@ -1,5 +1,5 @@
 AWSTemplateFormatVersion: '2010-09-09'
-Description: AWS Native Chef Server (auto-scaling HA) v4.1.0
+Description: AWS Native Chef Server (auto-scaling HA) v5.0.2
 
 Parameters:
   # Required Parameters
@@ -60,12 +60,18 @@ Parameters:
     Description: Enter how many licenses you have purchased
     Type: String
   DBInstanceClass:
-    Description: EC2 Instance type for RDS DBs (EBS Optimized instances recommended)
-    Default: 'db.m4.large'
+    Description: EC2 Instance type for RDS DBs (M5 class recommended for performance)
+    Default: 'db.m5.large'
     Type: String
-    AllowedValues: [db.t2.medium, db.t2.large, db.t2.xlarge, db.t2.2xlarge,
+    AllowedValues: [db.t3.small, db.t3.medium, db.t3.large, db.t3.xlarge, db.t3.2xlarge,
       db.m4.large, db.m4.xlarge, db.m4.2xlarge, db.m4.4xlarge, db.m4.10xlarge, db.m4.16xlarge,
-      db.r4.large, db.r4.xlarge, db.r4.2xlarge, db.r4.4xlarge, db.r4.8xlarge, db.r4.16xlarge]
+      db.r4.large, db.r4.xlarge, db.r4.2xlarge, db.r4.4xlarge, db.r4.8xlarge, db.r4.16xlarge,
+      db.m5.large, db.m5.xlarge, db.m5.2xlarge, db.m5.4xlarge, db.m5.12xlarge, db.m5.24xlarge]
+  DBStorageType:
+    Description: Select gp2 or io1 DB storage. io1 is much higher performing, must select minimum 100GB storage and an IOPS value
+    Default: 'gp2'
+    Type: String
+    AllowedValues: [gp2, io1]
   DBAllocatedStorage:
     Description: Storage size allocated for the database
     Default: '100'
@@ -74,6 +80,12 @@ Parameters:
     Description: IOPS allocated to the storage (storage size * 10)
     Default: '1000'
     Type: String
+  DBBackupDaystoKeep:
+    Description: Number of days of automatic backups to keep
+    Default: 7
+    Type: Number
+    MinValue: 0
+    MaxValue: 35
   ElasticSearchInstanceType:
     Description: The Instance type to use for ElasticSearch instances (Note, must have ephemeral storage, the instance type affects the total amount of elasticsearch storage. i3 strongly recommended)
     Type: String
@@ -84,35 +96,22 @@ Parameters:
       'm3.medium.elasticsearch', 'm3.large.elasticsearch', 'm3.xlarge.elasticsearch', 'm3.medium.elasticsearch',
       'r3.large.elasticsearch', 'r3.xlarge.elasticsearch', 'r3.2xlarge.elasticsearch', 'r3.4xlarge.elasticsearch', 'r3.8xlarge.elasticsearch' ]
   ElasticSearchVersion:
-    Description: Version of ElasticSearch to use. Chef 12.16 supports v2.3 or 5.x. (5.5 recommended for new installs)
+    Description: Version of ElasticSearch to use
     Type: String
-    Default: '5.5'
+    Default: '5.6'
     AllowedValues:
     - '2.3'
     - '5.3'
     - '5.5'
+    - '5.6'
   ElasticSearchShardCount:
     Description: Number of ElasticSearch hosts to provision at launch (3 recommended)
     Default: 3
     Type: Number
   ElasticSearchReplicaCount:
-    Description: Replication factor for ElasticSearch sha vrds (how many extra copies to keep)
+    Description: Replication factor for ElasticSearch shards (how many extra copies to keep)
     Default: 2
     Type: Number
-  ###############################################################################
-  # Package Versions & Locations
-  ChefServerPackage:
-    Description: The URL to the chef server EL7 (chef-server-core) package which will be downloaded
-    Type: String
-    Default: 'https://packages.chef.io/files/stable/chef-server/12.17.33/el/7/chef-server-core-12.17.33-1.el7.x86_64.rpm'
-  ChefManagePackage:
-    Description: The URL to the chef-manage EL7 package which will be downloaded
-    Type: String
-    Default: 'https://packages.chef.io/files/stable/chef-manage/2.5.16/el/7/chef-manage-2.5.16-1.el7.x86_64.rpm'
-  PushJobsPackage:
-    Description: The URL to the push jobs server package which will be downloaded
-    Type: String
-    Default: 'https://packages.chef.io/files/stable/opscode-push-jobs-server/2.2.8/el/7/opscode-push-jobs-server-2.2.8-1.el7.x86_64.rpm'
   ###############################################################################
   # Security Settings
   LoadBalancerScheme:
@@ -166,27 +165,27 @@ Parameters:
     Default: ''
     Type: String
     Description: The S3 location of a custom chef-server configuration snippet that will be injected into the chef-server.rb (optional)
+  SupermarketUrl:
+    Description: The URL of the Private Supermarket Server, for oc-id authentication.  Leave blank to disable.
+    Type: String
+    Default: ''
   Route53HostedZone:
     Type: String
     Default: ''
-    Description: Supply a Route 53 Hosted Zone name (eg. mydomain.com.) for auto-creating a DNS record. Must end in a dot. (Leave blank to disable)
+    Description: Supply a Route 53 Hosted Zone name (eg. mydomain.com) for auto-creating a DNS record. Must NOT end in a dot. (Leave blank to disable)
   Route53RecordName:
     Type: String
     Default: 'chef'
     Description: Supply a DNS record name that will be prepended to the Route 53 Hosted Zone
-  AMIFlavor:
-    Description: Choose the AMI Flavor, the High-Perf CentOS image or the stock and paid official RHEL image
-    Type: String
-    Default: 'centos'
-    AllowedValues:
-    - 'centos'
-    - 'rhel'
   SystemLogsGroup:
     Description: The logical name of the Cloudwatch Logs log group for systemn logs
     Type: String
   AppLogsGroup:
     Description: The logical name of the Cloudwatch Logs log group for systemn logs
     Type: String
+  TemplateVersion:
+    Type: String
+    Default: "5.0.2"
 
 Metadata:
   cfn-lint:
@@ -197,8 +196,6 @@ Metadata:
 Conditions:
   CreateRoute53Record:
     !Not [!Equals [ !Ref Route53HostedZone, '' ] ]
-  RHELAmiFlavor:
-    !Equals [ !Ref AMIFlavor, 'rhel' ]
 
 Resources:
 # Frontend Autoscale Groups
@@ -426,19 +423,8 @@ Resources:
       UserData:
         "Fn::Base64": !Sub |
           #!/bin/bash -ex
-          trap "{
-            /opt/aws/bin/cfn-signal -e 1 --region ${AWS::Region} --stack ${AWS::StackName} --resource ServerLaunchConfig
-            # Uncomment this next line before going to production
-            # aws autoscaling set-instance-health --health-status Unhealthy --region ${AWS::Region} --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id)
-          }" ERR
-          # Update the system first
-          yum upgrade -y
-          # Run before script, make sure to install cfn-init if not installed
-          # attempt to fetch the script first as a signed request (private bucket), then unsigned (public bucket)
-          aws s3 cp s3://${AutomationBucket}/files/before.sh /root/before.sh || \
-            curl -s https://${AutomationBucket}.s3.amazonaws.com/files/before.sh -o /root/before.sh || \
-            curl -s https://aws-native-chef-server.s3.amazonaws.com/files/before.sh -o /root/before.sh
-          bash -ex /root/before.sh
+          # Uncomment this next line before going to production, note: It can cause instances to cycle rapidly, watch Cloudwatch Logs for errors
+          # trap "aws autoscaling set-instance-health --health-status Unhealthy --region ${AWS::Region} --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id)" ERR
           # Execute AWS::CloudFormation::Init
           /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource ServerLaunchConfig --region ${AWS::Region}
           # All is well so signal success and let CF know wait function is complete
@@ -446,12 +432,9 @@ Resources:
     Metadata:
       AWS::CloudFormation::Init:
         configSets:
-          default: [awslogs, es_proxy_setup, chef_server_setup, filebeat]
+          default: [awslogs, es_proxy_setup, chef_server_setup, filebeat, final_stage]
         es_proxy_setup:
           files:
-            /usr/local/bin/aws-signing-proxy:
-              source: https://github.com/chef-customers/aws-signing-proxy/releases/download/v0.5.0/aws-signing-proxy
-              mode: '000755'
             /etc/systemd/system/aws-signing-proxy.service:
               content: |
                 [Unit]
@@ -474,21 +457,9 @@ Resources:
                 stdout-log: true
           commands:
             01_start_es_proxy:
-              command: systemctl daemon-reload && systemctl start aws-signing-proxy
+              command: |
+                systemctl daemon-reload && systemctl start aws-signing-proxy
         chef_server_setup:
-          packages:
-            rpm:
-              chef-server-core: !Sub ${ChefServerPackage}
-              chef-manage: !Sub ${ChefManagePackage}
-              opscode-push-jobs-server: !Sub ${PushJobsPackage}
-            yum:
-              perl: []
-              perl-DateTime: []
-              perl-Sys-Syslog: []
-              perl-LWP-Protocol-https: []
-              perl-Digest-SHA: []
-              zip: []
-              unzip: []
           files:
             /etc/opscode-push-jobs-server/opscode-push-jobs-server.rb:
               content: !Sub |
@@ -538,34 +509,27 @@ Resources:
                 rabbitmq['queue_length_monitor_enabled'] = false
                 opscode_expander['enable'] = false
                 dark_launch['actions'] = false
-                oc_id['applications'] ||= {}
-                oc_id['applications']['supermarket'] = {
-                  'redirect_uri' => 'https://supermarket.${Route53HostedZone}/auth/chef_oauth2/callback'
-                }
+                unless '${SupermarketUrl}'.empty?
+                  oc_id['applications'] ||= {}
+                  oc_id['applications']['supermarket'] = {
+                    'redirect_uri' => '${SupermarketUrl}/auth/chef_oauth2/callback'
+                  }
+                end
                 default_orgname '${ChefDefaultOrgName}'.empty? ? null : '${ChefDefaultOrgName}'
                 # special handling for Chef Automate URL and Token which might be empty strings
                 unless '${ChefAutomateServerUrl}'.empty? || '${ChefAutomateToken}'.empty?
-                  data_collector['root_url'] = '${ChefAutomateServerUrl}'
+                  data_collector['root_url'] = '${ChefAutomateServerUrl}/data-collector/v0/'
                   data_collector['token'] = '${ChefAutomateToken}'
+                  profiles['root_url'] = '${ChefAutomateServerUrl}'
                 end
               - { DNSNAME: !If [CreateRoute53Record, !Sub "${Route53RecordName}.${Route53HostedZone}", !GetAtt ChefALB.DNSName] }
-            /etc/sysctl.d/00-chef.conf:
-              content: |
-                vm.swappiness=10
-                vm.max_map_count=262144
-                vm.dirty_ratio=20
-                vm.dirty_background_ratio=30
-                vm.dirty_expire_centisecs=30000
-            /etc/security/limits.d/20-nproc.conf:
-              content: |
-                *   soft  nproc     65536
-                *   hard  nproc     65536
-                *   soft  nofile    1048576
-                *   hard  nofile    1048576
           commands:
             02_before_script:
               command: !Sub |
-                sysctl -p /etc/sysctl.d/00-chef.conf
+                # If we're using a marketplace, install locally cached packages
+                pushd /var/cache/marketplace
+                rpm -ivh chef-server-core.rpm chef-manage.rpm push-jobs-server.rpm
+                popd
                 if [ -n '${ChefServerCustomConfig}' ]; then
                     aws s3 cp ${ChefServerCustomConfig} /etc/opscode/chef-server-custom.rb
                     echo "# Appended from chef-server-custom.rb" >> /etc/opscode/chef-server.rb
@@ -577,29 +541,13 @@ Resources:
                 export BUCKET=${ChefSecretsBucket}
                 export AWS_REGION=${AWS::Region}
                 export WAITHANDLE="${WaitHandle}"
-                # attempt to fetch the script first as a signed request (private bucket), then unsigned (public bucket)
-                aws s3 cp s3://${AutomationBucket}/files/main.sh /root/main.sh || \
-                  aws s3 cp --no-sign-request s3://${AutomationBucket}/files/main.sh /root/main.sh
-                bash -x /root/main.sh
-            04_after_script:
-              command: !Sub |
-                # attempt to fetch the script first as a signed request (private bucket), then unsigned (public bucket)
-                aws s3 cp s3://${AutomationBucket}/files/after.sh /root/after.sh || \
-                  curl -s https://${AutomationBucket}.s3.amazonaws.com/files/after.sh -o /root/after.sh
-                bash -ex /root/after.sh
+
+                bash -x /var/cache/marketplace/main.sh
             05_configure_cloudwatch_monitoring:
               command: |
-                mkdir /opt/cloudwatch_monitoring
-                cd /opt/cloudwatch_monitoring
-                curl http://aws-cloudwatch.s3.amazonaws.com/downloads/CloudWatchMonitoringScripts-1.2.1.zip -O
-                unzip CloudWatchMonitoringScripts-1.2.1.zip
-                rm -f CloudWatchMonitoringScripts-1.2.1.zip
                 crontab -l | { cat; echo "*/5 * * * * /opt/cloudwatch_monitoring/aws-scripts-mon/mon-put-instance-data.pl --auto-scaling --mem-util --disk-space-util --disk-path=/ --from-cron"; } | crontab -
         awslogs:
           files:
-            /root/awslogs-agent-setup.py:
-              source: 'https://s3.amazonaws.com/aws-cloudwatch/downloads/latest/awslogs-agent-setup.py'
-              mode: '000755'
             /etc/awslogs/awscli.conf:
               content: !Sub |
                 [default]
@@ -706,11 +654,8 @@ Resources:
             01_setup:
               command: !Sub |
                 mkdir -p /var/lib/awslogs
-                python /root/awslogs-agent-setup.py --region ${AWS::Region} --non-interactive -c /etc/awslogs/awslogs.conf
+                python /var/cache/marketplace/awslogs-agent-setup.py --region ${AWS::Region} --non-interactive -c /etc/awslogs/awslogs.conf
         filebeat:
-          packages:
-            rpm:
-              filebeat: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-5.6.6-x86_64.rpm
           files:
             /etc/filebeat/filebeat.yml:
               content: |
@@ -732,7 +677,18 @@ Resources:
               group: root
           commands:
             01_systemd:
-              command: systemctl daemon-reload && systemctl start filebeat.service
+              command: |
+                rpm -ivh /var/cache/marketplace/filebeat-5.6.6-x86_64.rpm
+                systemctl daemon-reload && systemctl start filebeat.service
+        final_stage:
+          commands:
+            09_cleanup:
+              command: |
+                # clean up the chef package cache, to maximize available disk space after install
+                if [ -d /var/cache/marketplace ]; then
+                    rm -f /var/cache/marketplace/*.rpm
+                    rm -f /var/cache/marketplace/*.aib
+                fi
 
   WaitCondition:
     Type: AWS::CloudFormation::WaitCondition
@@ -749,7 +705,7 @@ Resources:
   PostgreSQLStack:
     Type: AWS::CloudFormation::Stack
     Properties:
-      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/chef_rds.yaml
+      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/${TemplateVersion}/chef_rds.yaml
       Parameters:
         VPC: !Sub ${VPC}
         ChefServerSubnets: !Join [ ",", !Ref ChefServerSubnets ]
@@ -757,8 +713,10 @@ Resources:
         ContactEmail: !Ref ContactEmail
         ContactDept: !Ref ContactDept
         DBInstanceClass: !Ref DBInstanceClass
+        DBStorageType: !Ref DBStorageType
         DBAllocatedStorage: !Ref DBAllocatedStorage
         DBIops: !Ref DBIops
+        BackupDaystoKeep: !Ref DBBackupDaystoKeep
         FrontendSecurityGroupId: !Ref FrontendSecurityGroupId
         AlertNotificationTopic: !Ref AlertNotificationTopic
 
@@ -767,7 +725,7 @@ Resources:
   ElasticsearchStack:
     Type: AWS::CloudFormation::Stack
     Properties:
-      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/chef_elasticsearch.yaml
+      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/${TemplateVersion}/chef_elasticsearch.yaml
       Parameters:
         VPC: !Sub ${VPC}
         ChefServerSubnets: !Join [ ",", !Ref ChefServerSubnets ]
@@ -786,9 +744,9 @@ Resources:
     Type: AWS::Route53::RecordSet
     Condition: CreateRoute53Record
     Properties:
-      HostedZoneName: !Ref Route53HostedZone
+      HostedZoneName: !Sub ${Route53HostedZone}.
+      Name: !Sub ${Route53RecordName}.${Route53HostedZone}.
       Comment: !Sub Created by Cloudformation ${AWS::StackName}
-      Name: !Sub ${Route53RecordName}.${Route53HostedZone}
       Type: CNAME
       TTL: '900'
       ResourceRecords:
@@ -800,7 +758,7 @@ Resources:
   OpsDashboardStack:
     Type: AWS::CloudFormation::Stack
     Properties:
-      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/chef_server_ops_dashboard.yaml
+      TemplateURL: !Sub https://s3.amazonaws.com/${AutomationBucket}/${TemplateVersion}/chef_server_ops_dashboard.yaml
       Parameters:
         BootstrapAutoScaleGroup: !Ref BootstrapAutoScaleGroup
         FrontendAutoScaleGroup: !Ref FrontendAutoScaleGroup
@@ -831,7 +789,7 @@ Resources:
         - Name: MountPath
           Value: '/'
         - Name: Filesystem
-          Value: !If [RHELAmiFlavor, "/dev/nvme0n1p2", "/dev/nvme0n1p1"]
+          Value: '/dev/nvme0n1p1'
 
   BootstrapDiskSpaceUtilizationNvme:
     Type: AWS::CloudWatch::Alarm
@@ -853,7 +811,7 @@ Resources:
         - Name: MountPath
           Value: '/'
         - Name: Filesystem
-          Value: !If [RHELAmiFlavor, "/dev/nvme0n1p2", "/dev/nvme0n1p1"]
+          Value: '/dev/nvme0n1p1'
 
   MemoryUtilization:
     Type: AWS::CloudWatch::Alarm
